const constants = {
  SET_LEVEL: 'SET_LEVEL',
  SET_CENTER: 'SET_CENTER',
  SET_ZOOM: 'SET_ZOOM',
  ADD_OPTION: 'ADD_OPTION',
  CLEAR_OPTION: 'CLEAR_OPTION',
  SET_DR: 'SET_DR',
  CLEAR_DR: 'CLEAR_DR',
  SET_DGR: 'SET_DGR',
  CLEAR_DGR: 'CLEAR_DGR',
  SET_HOVER_INFO: 'SET_HOVER_INFO',
  CLEAR_HOVER_INFO: 'CLEAR_HOVER_INFO',
  SET_HOVER_AGENCY: 'SET_HOVER_AGENCY',
  CLEAR_HOVER_AGENCY: 'CLEAR_HOVER_AGENCY',
  SET_MAP: 'SET_MAP',
  SET_DATA: 'SET_DATA',
  CLEAR_DATA: 'CLEAR_DATA'
}

export default constants